### ISSUE TITLE
add license info to bottom of web site

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#10]
Apparently since we're using some info from the MG wiki, we need to have the same license as what's shown at the bottom of this page:
https://docs.megaglest.org/G3D_support

That info can be modified and put on the bottom of *our* page.

https://github.com/ZetaGlest/zetaglest.github.io/blob/f2205885e1a90e67f78eaf31df3cbe31d49c2180/docs/templates/tail.html#L10

The graphic can be put in https://github.com/ZetaGlest/zetaglest.github.io/tree/master/docs/assets/images

**Comment by AlexErling** [comment]
Hi, I am new to open source. Can I take this on? It seems pretty explanatory, anything else I need to know?

**Comment by andy5995** [comment]
Thanks for the offer, @AlexErling .

Once tail.html is edited, normally you'd need to generate the site by building and running docs/src/simplecgen

Since you're new, I'll say that if you have any trouble compiling it, then don't worry about testing your changes. You can just do the PR for tail.html and someone else can generate the site and test.

However, if you'd like to compile and test your changes, and learn a bit along the way, please do so, and join our Discord channel.

**Comment by AlexErling** [comment]
<img width="1425" alt="footerphoto" src="https://user-images.githubusercontent.com/29783432/39828018-3562246e-537f-11e8-93f3-02b6c1bd3b71.png">

Okay, thanks, I will let you know if I run into any issues compling it. Just to clarfiy, you would like to to the add content is available under... line and the images in the bottom right corner. What graphic do I need to put in the tail.html?

**Comment by andy5995** [comment]
At the bottom, before the "powered by" statement.

>What graphic do I need to put in the tail.html?

This one:

![cc-by-sa](https://user-images.githubusercontent.com/16764864/39840854-6f97583a-53a6-11e8-90a1-ebbc738708f2.png)

So.. text + graphic link.

**Comment by AlexErling** [comment]
Here are the changes I've made. I couldn't get the files to compile to check out the changes so I might need help with that. Should I still send in the pull request, so someone else can check out the changes?

Changes
```
  <p class= "sct_footer">
    Content is available under <a href="https://creativecommons.org/licenses/by-sa/3.0/" title ="Creative Commons Attribution" target="_blank">Creative Commons Attribution Share Alike</a> unless otherwise noted.
    <a href="https://creativecommons.org/licenses/by-sa/3.0/" title ="Creative Commons Attribution" target="_blank">
      <img src="images/cc-by-sa.png" alt="Creative Commons" />
    </a>
```

**Comment by andy5995** [comment]
You can either do the PR and we'll test it, or work with us on Discord to compile the simplecgen program. Your choice. :)

(You may have to wait until tomorrow to get help with simplecgen though)

Thanks @AlexErling
