### ISSUE TITLE
calc_cost_of_unit repeats infinitely in some cases

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#3]
This function suffers from infinite recursion when a unit can morph back into the same unit it was originally.

The problem is happening because of these 3 [units from the Great Ming](https://github.com/ZetaGlest/zetaglest-data/tree/develop/techs/zetapack/factions/the_great_ming/units), which can morph into the unit (shown on the right).

ying_che -> ying_che_
ying_che_ -> ying-che
ying-che -> ying_che

https://github.com/ZetaGlest/zetaglest.github.io/blob/538a02cbf3412af0d8f9dcd9b5a4578361516051/convert_faction_xml2html/convert_faction_xml2html.pl#L2136-L2171

To generate the site, I temporarily disabled the ying_che_'s ability to morph, and removed the ying-che. After the site was generated, I reverted the changes.

**Comment by mathusummut** [comment]
I've never used Perl, but there should be a way to store previously "visited" units in a HashTable and check whether the unit is already in the hast table before evaluating it.

**Comment by andy5995** [comment]
Other units that this affects:

worker / ikki_mob (Japanese)

large container / air container (Specialists)
