### ISSUE TITLE
add link to screenshots

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#34]
We have a link to screenshots in the README, but not on the web site.

right now, our screenshots are in a repo

https://github.com/ZetaGlest/screenshots

That link should be added between these 2 lines:

https://github.com/ZetaGlest/zetaglest.github.io/blob/069ef6f245c0685f1215f39cc601e4d668061faf/docs/templates/default.html#L14-L15

If you're interested in working on this, please post on this ticket before you start.

*Please remember to **star** this project (upper right-hand corner)*

**Comment by simon-c-wong** [comment]
May I try to tackle this issue?

**Comment by mathusummut** [comment]
Yes definitely :)

**Comment by andy5995** [comment]
@scwong93 Hello, and thank you for your pull request.

You'll want to edit your local git config email settings so GitHub records your contributions properly. See https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/  and https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup for details on how to fix your configuration.

Let me know if you have any questions.
