### ISSUE TITLE
edit links can be removed from page:lua scripting sound

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#38]
edit links can be removed:

~~https://github.com/ZetaGlest/zetaglest.github.io/blob/master/docs/infiles/lua_scripting_sound.sct~~

If you're interested in working on this, please post on this ticket before you start.

*Please remember to **star** this project (upper right-hand corner)*

**Comment by andy5995** [comment]
We switched to using jekyll today to generate the website. As a result, the file that needs editing is now https://github.com/ZetaGlest/zetaglest.github.io/blob/master/docs/lua_scripting.html (the sound section)

https://github.com/ZetaGlest/zetaglest.github.io/blob/4fb0a3bb87ac3c8390faa431a7f6114e962b5963/docs/lua_scripting.html#L472-L490

**Comment by tharunjose** [comment]
@andy5995 let me fix this. There are edit links in the Game, AI, Events and XML events sections as well. Shall I remove those too?

**Comment by andy5995** [comment]
Hi @tharunjose .

>There are edit links in the Game, AI, Events and XML events sections as well. Shall I remove those too?

Yes, thank you.
