### ISSUE TITLE
docs home page doesn't validate

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#53]
The [docs home page](https://zetaglest.github.io/docs/) doesn't validate.

https://validator.w3.org/nu/?doc=https%3A%2F%2Fzetaglest.github.io%2Fdocs%2F

If you're interested in working on this, please post on this ticket before you start.

*Please remember to **star** this project (upper right-hand corner)*

**Comment by tharunjose** [comment]
@andy5995 I'll look into this.

**Comment by andy5995** [comment]
ok @tharunjose
