### ISSUE TITLE
new program for analyzing xml data and outputting to web page

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#54]
Right now we have a perl script that can read the xml files in these directories:

https://github.com/ZetaGlest/zetaglest-data/tree/develop/techs/zetapack/factions

The output looks something like this:

https://zetaglest.github.io/greece_overview.html

But I've heard complaints that it's dependency hell to use the script, esp. on Windows. Typically the script only needs to be run by administrators, to update the web site and game unit information. But it's important that other people to be able to run it, so they can test it and contribute patches.

Anybody wanting to work on this could use whatever language they liked.

Another problem with the current perl script is issue #3.

If you're interested in working on this, please post on this ticket before you start.

*Please remember to **star** this project (upper right-hand corner)*

**Comment by joaomarcoscsilva** [comment]
I'll try to do it in python. It's portable and I've been interested in xml parsing for quite a while.
I may need some help with the html formatting though.

**Comment by andy5995** [comment]
I'd be happy to help you with the HTML formatting if you need it.

And speaking of html, it would be best if we could separate that from the python code. Easier to design and maintain the code that way.

The html would be in templates, we'd probably need at least 3 of them:

1. For the [main summary page](https://zetaglest.github.io/)
2. For the [faction pages](https://zetaglest.github.io/medieval_overview.html) that list each unit from that faction
3. For the [unit page](https://zetaglest.github.io/medieval_armored_axeman_full.html)

So I or someone else could work on the templates.

If you need a clearer understanding on how that would be done, you may get an idea by looking at this C project https://github.com/theimpossibleastronaut/simplecgen

And to be honest, I don't have a clear idea yet on how it will work, but I'm quite confident that combining templates with your python code will make it easier. If you get any ideas, or have questions let me know. I'll give it some thought in the meanwhile.

**Comment by andy5995** [comment]
Not sure if this will be helpful, but my current output with the perl script

https://gist.githubusercontent.com/andy5995/7c788676ea58ea1aefc4e69a2b98b2ac/raw/0b2eb59af5ab4efa2e5d005250956f600160cc70/gistfile1.txt

That's of course without the japanese and ming factions (I have to move them outside the zetapack tech folder because of #3 )
