### ISSUE TITLE
new favicon.ico needed

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#75]
This needs to be replaced, this ticket is dependent on https://github.com/ZetaGlest/zetaglest-source/issues/250

We should be able to adapt any new icons in that ticket to replace this one used for the web site.

![image](https://user-images.githubusercontent.com/16764864/46262831-a24b0c80-c4cc-11e8-8225-485a0ae0bf47.png)

**Comment by parammittal16** [comment]
I want to work on this issue

**Comment by andy5995** [comment]
Someone just offered to redesign the icons to complete the ticket that I linked to above. Once that is completed and approved, the favicon can be replaced with the new zetaglest.ico

**Comment by mathusummut** [comment]
[The new favicon is now in place.](https://github.com/ZetaGlest/zetaglest.github.io/commit/c61dcc0d9d3ae95a3cc7e6927fd54e4bb248faeb)
