### ISSUE TITLE
add search box

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#88]
site needs a search box.

it's running on github pages, so limited to javascript and jquery.

Examples of how this can be done can be seen on other jekyll and github hosted projects

https://github.com/mhwkb/mhwkb.github.io
https://github.com/jekyll/jekyll
https://github.com/up-for-grabs/up-for-grabs.net

The search box should be located in the lower-left of the main menu left-hand pane of the default layout.

Please remember to "star" this project.

**Comment by marjanovicsteva** [comment]
I'm working on it
