### ISSUE TITLE
mobile-friendly faction docs

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#89]
@escottalexander 
>Responsive design is hard on a table. If we make the categories stack then it won't be clear which box goes with which label. Any ideas on how we can change it? One I have is to make it so that on mobile, all you see is a list of unit names until you click on one specific name, then it shows the info that goes with that unit. Thoughts? 

>Also, this will need to be addressed when we build the JSON to HTML conversion function.

**Comment by linux-player9** [comment]
You should add a button to switch between the mobile and the desktop version of the page. So that evryone can choose the mode he prefer

**Comment by andy5995** [comment]
>You should add a button to switch between the mobile and the desktop version of the page. So that evryone can choose the mode he prefer

@linux-player9 Thanks for pointing that out. It needs to be on a separate ticket.
