### ISSUE TITLE
Docs web page for lua scripting doesn't pass validation

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#90]
This page doesn't validate.

https://zetaglest.github.io/docs/lua_scripting.html

The results of the validation are at https://validator.w3.org/nu/?doc=https%3A%2F%2Fzetaglest.github.io%2Fdocs%2Flua_scripting.html

**Comment by andy5995** [comment]
Only 5 errors left! Thanks @tharunjose 

https://validator.w3.org/nu/?doc=https%3A%2F%2Fzetaglest.github.io%2Fdocs%2Flua_scripting.html

**Comment by mathusummut** [comment]
This is fixed now
