### ISSUE TITLE
web page for g3d plugin doesn't pass validation

### ISSUE THREAD

**Issue by andy5995** [glest/glest.io#91]
The page is at

https://zetaglest.github.io/docs/modelling/g3d_blender.html

The results of the validation are at https://validator.w3.org/nu/?doc=https%3A%2F%2Fzetaglest.github.io%2Fdocs%2Fmodelling%2Fg3d_blender.html

**Comment by shad-k** [comment]
@andy5995 I'd like to take this up.

**Comment by mathusummut** [comment]
This is fixed now
